#!/bin/bash

brewPhp71="$(brew --prefix homebrew/php/php71)/bin"

`echo $PATH | grep ${brewPhp71} >/dev/null`

if [ $? == 0 ]; then
	return 0;
fi

if [[ `uname` == 'Darwin' ]]; then
	export PATH="${brewPhp71}:$PATH"
fi

