#!/bin/bash

tput el
echo -n "setting up glcoud sdk" $'\r'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/vbruxeljr/.google-cloud-sdk/path.bash.inc' ]; then . '/Users/vbruxeljr/.google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/vbruxeljr/.google-cloud-sdk/completion.bash.inc' ]; then . '/Users/vbruxeljr/.google-cloud-sdk/completion.bash.inc'; fi
