#!/bin/bash

export greenPs1='\[\e[1;32m\]\u@$(hostname -f)\[\e[0;32m\] \w\[\e[0m\]\$ '
export yellowPs1='\[\e[1;33m\]\u@$(hostname -f)\[\e[0;33m\] \w\[\e[0m\]\$ '
export redPs1='\[\e[1;31m\]\u@$(hostname -f)\[\e[0;31m\] \w\[\e[0m\]\$ '
