#!/bin/bash

tput el
echo -n "defining alias" $'\r'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

if [ `uname` == 'Linux' ]; then
	alias ls='ls --color'
fi

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias tree='tree -C --dirsfirst'

alias pwd='pwd -P'
alias mkdir='mkdir -p'


