#!/bin/bash

tput el
echo -n "defining PS1 colors" $'\r'

export bluePs1='\[\e[1;34m\]\u@$(hostname -f)\[\e[0;34m\] \w\[\e[0m\]\$ '
export cyanPs1='\[\e[1;36m\]\u@$(hostname -f)\[\e[0;36m\] \w\[\e[0m\]\$ '
export greenPs1='\[\e[1;32m\]\u@$(hostname -f)\[\e[0;32m\] \w\[\e[0m\]\$ '
export yellowPs1='\[\e[1;33m\]\u@$(hostname -f)\[\e[0;33m\] \w\[\e[0m\]\$ '
export purplePs1='\[\e[1;35m\]\u@$(hostname -f)\[\e[0;35m\] \w\[\e[0m\]\$ '
export redPs1='\[\e[1;31m\]\u@$(hostname -f)\[\e[0;31m\] \w\[\e[0m\]\$ '

