#!/bin/bash

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

if [ `uname` == 'Linux' ]; then
	alias ls='ls --color'
fi

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias tree='tree -C --dirsfirst'

alias pwd='pwd -P'
alias mkdir='mkdir -p'

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

