#!/bin/bash

echo 'add your public ssh key to ssh agent'

public_key="${HOME}/.ssh/id_rsa"

if [[ ! -f ${public_key} ]]; then
    echo '[bash.d] Unable to start SSH Agent. No public ssh key found.'
    return;
fi

eval $( ssh-agent ) >/dev/null

ssh-add ${public_key} &>/dev/null

