#!/bin/bash

#
# adds your public ssh key to ssh agent
#

public_key="${HOME}/.ssh/id_rsa"

if [[ ! -f ${public_key} ]]; then
    echo '[bash.d] Unable to start SSH Agent. No public ssh key found.'
    return;
fi

if [[ -d "${HOME}/.bash.d/vendor/ssh-agent" ]]; then
    source ${HOME}/.bash.d/vendor/ssh-agent/ssh-find-agent.sh -a || eval $(ssh-agent) > /dev/null
else
    eval $( ssh-agent ) >/dev/null
fi

ssh-add ${public_key} &>/dev/null

alias ssh='ssh -A'

