#!/bin/bash

#
# adds your public ssh key to ssh agent
#

public_key="${HOME}/.ssh/id_rsa"

if [[ ! -f ${public_key} ]]; then
    echo 'Unable to start SSH Agent. No public ssh key found.'
    return;
fi

ssh-agent 1>/dev/null
ssh-add ${public_key} &>/dev/null

alias ssh='ssh -A'

