#!/bin/bash

if [ `uname` != 'Darwin' ]; then
	return 0;
fi

tput el
echo -n "configuring brew" $'\r'

brewPhp71="$(brew --prefix php@7.1)/bin"

if [ -d $brewPhp71 ]; then
    `echo $PATH | grep ${brewPhp71} >/dev/null`

    if [ $? == 0 ]; then
        export PATH="${brewPhp71}:$PATH"
    fi
fi

