#!/bin/bash

if [ `uname` == 'Darwin' ]; then
    tput el
    echo -n "defining ls colors" $'\r'
    export CLICOLOR=1
    export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd

    # Setting for the new UTF-8 terminal support in Lion
    export LC_CTYPE=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
fi

